### ISSUE TITLE
RuntimeError for nonexistent attribute/method 'crow_indices' of type Tensor'.

### ISSUE THREAD

**Issue by simonpun123** [twitter-research/graph-neural-pde#23]
Hi there, I have installed the packages as stated in README.md and tried to run script run_GNN.py. It turns of I got a RuntimeError with the error message as follows: 

Traceback (most recent call last):
  File "run_GNN.py", line 7, in <module>
    from torch_geometric.nn import GCNConv, ChebConv  # noqa
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/local/lib/python3.7/dist-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/usr/local/lib/python3.7/dist-packages/torch_sparse/__init__.py", line 41, in <module>
    from .tensor import SparseTensor  # noqa
  File "/usr/local/lib/python3.7/dist-packages/torch_sparse/tensor.py", line 13, in <module>
    class SparseTensor(object):
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py", line 974, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py", line 67, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError: 
Tried to access nonexistent attribute or method 'crow_indices' of type 'Tensor'.:
  File "/usr/local/lib/python3.7/dist-packages/torch_sparse/tensor.py", line 109
    def from_torch_sparse_csr_tensor(self, mat: torch.Tensor,
                                     has_value: bool = True):
        rowptr = mat.crow_indices()
                 ~~~~~~~~~~~~~~~~ <--- HERE
        col = mat.col_indices()

Can anyone explain it and maybe try to help me resolve this? Thank you

Best regards,
Simon

**Comment by simonpun123** [comment]
Hi, I fixed the issue by downgrading the torch packages used in the codes.

**Comment by amblee0306** [comment]
> Hi, I fixed the issue by downgrading the torch packages used in the codes.

Hi,  I am facing the same issue, can I know to what version did you downgrade the packages to?

**Comment by alanjohnvarghese** [comment]
Hi!

I too was facing the same issue. I fixed it by using the versions mentioned in the [pyG_install.sh](https://github.com/twitter-research/graph-neural-pde/blob/main/pyG_install.sh) file

**Comment by simonpun123** [comment]
> > Hi, I fixed the issue by downgrading the torch packages used in the codes.
> 
> Hi, I am facing the same issue, can I know to what version did you downgrade the packages to?

Sorry, I forgot. You may follow the version listed in the README file.
